Update sgp40.py
nevermore3d/Nevermore_Max pull request #7
Opened 2023-11-14 11:51 UTC by stansfie

Hi Nevermore team,

First time writing a github pull, so hope it works!

**Changes to syp40.py**
- Added 'plot_voc' boolean to output only voc vs all parameters
- Added 'voc_scale' float to adjust the scale for voc output for plotting (e.g., 0.5)
- Added INITIALIZE to _init_sgp40
- Removed FEATURE_SET from _init_sgp40 - performs soft reset and results in "unable to write to i2c_device" error from some sgp40 chips
- Removed SOFT_RESET - results in "unable to write to i2c_device" error from some sgp40 chips
- Changed featureset output to 0x3200 from 0x3240 as per Adafruit discussion forums (https://forums.adafruit.com/viewtopic.php?t=202391)

**Humidity correction**
The other neat thing in most printers with organic filters is that they're closed chambers. Relative humidity is therefore a function of change in saturation vapor pressure with temperature with an assumed constant water volume (g/g). With a single chamber thermostat humidity can be corrected assuming a closed chamber.

**Klipper**
Example Klipper config to turn on a nevermore micro in a closed chamber when VOC >120.

_Hardware_
- SGP40 
- Nevermore micro
- Chamber temperature sensor 'chamber'

_Installation_
SGP40 connected to raspberry pi host on i2c.1

printer.cfg:

`## fan - Nevermore Micro with VOC PID control`
`[sgp40]`

`[temperature_sensor chamber]`
`;define your chamber sensor`

`[temperature_fan VOC/2]`
`pin: ; Your Nevemore pin here`
`kick_start_time: 0`
`#shutdown_speed: 0`
`off_below: 0.2`
`max_power: 1.0`
`#fan_speed: 0.6`
`sensor_type: SGP40`
`i2c_mcu: host`
`i2c_bus: i2c.1`
`i2c_speed: 400000`
`voc_scale: 0.5  #set to 50% to enable plotting at a resonable scale`
`ref_temp_sensor: temperature_sensor chamber`
`# ref_humidity_sensor:`
`#min_temp: 0`
`#max_temp: 500`
`control: pid`
`min_temp: 40`
`max_temp: 300`
`#max_delta: 5.0`
`pid_kp: 1`
`pid_ki: 0.2`
`pid_kd: 2.0`
`pid_deriv_time: 5.0`
`min_speed: 0.`
`max_speed: 1.0`
`target_temp: 60 #VOC 120 at voc_scale: 0.5`

**Mainsail output**
<img width="676" alt="Screenshot 2023-11-14 at 8 15 48 pm" src="https://github.com/nevermore3d/Nevermore_Max/assets/25702159/a0bed6fa-e39f-44ea-817c-aabfa8105167">

2023-11-14 18:18 UTC, SanaaHamel requested changes
tl;dr: Some good, most bad.

Papering over I2C comm issues by commenting out checks can work for your machine, but isn't an acceptable general solution.

2023-11-14 18:18 UTC, SanaaHamel commented on Software/Klipper/sgp40.py
> +        #    logging.exception("sgp40: Self test error")
The failure you described is an I2C comm issue. It doesn't make sense to plaster over the problem by disabling the self-test.

2023-11-14 18:18 UTC, SanaaHamel commented on Software/Klipper/sgp40.py
> +
Just remove it entirely.
1) If I interpret the data sheet correctly this is a general call reset so everyone on the bus is supposed to restart, which is extremely rude to other systems.
2) Wouldn't work anyways. General calls are issued to address 0x00. This issues to the SGP40 address and sends a nonsense opcode.

2023-11-14 18:18 UTC, SanaaHamel commented on Software/Klipper/sgp40.py
> +        self._callback(self.mcu.estimated_print_time(measured_time), self.voc * self.voc_scale)
Why scale the callback but not the `get_status` result?

2023-11-14 18:18 UTC, SanaaHamel commented on Software/Klipper/sgp40.py
> +            logging.exception("sgp40: Serial number does not match")
I have no idea what you're trying to do here.
1) The serial # op is pure, so IDK why bother if you're not going to log the serial # or something
2) Why exclude higher serial #s?

2023-11-14 18:46 UTC, SanaaHamel commented on Software/Klipper/sgp40.py
>      "FEATURE_SET" : [0x20, 0x2F],
`0x202F` was an op-code from the SGP30 device, and isn't officially supported by the SGP40.
Why was this ever used?

2023-11-15 09:10 UTC, stansfie commented on Software/Klipper/sgp40.py
> +        # if feature_set[0] != 0x3200:
Done

2023-11-15 09:10 UTC, stansfie commented on Software/Klipper/sgp40.py
> +    "INITIALIZE" : [0x36, 0x82],
Renamed INITIALIZE to GET_SERIAL, but removed calls to get a serial number as it's not strictly needed

2023-11-15 09:10 UTC, stansfie commented on Software/Klipper/sgp40.py
> +        #    logging.exception("sgp40: Self test error")
Oops. This is back

2023-11-15 09:10 UTC, stansfie commented on Software/Klipper/sgp40.py
> +
Done

2023-11-15 09:10 UTC, stansfie commented on Software/Klipper/sgp40.py
> +        self._callback(self.mcu.estimated_print_time(measured_time), self.voc * self.voc_scale)
Great point - this is also done

2023-11-15 09:13 UTC, stansfie commented on Software/Klipper/sgp40.py
> +            logging.exception("sgp40: Serial number does not match")
I've removed the call to get the serial number; it's not required and I initially saw it in a sensirion initialization routine. The only call to sgp40 that's really needed in the _init_sgp40 is the self_test which you pointed out above.

2023-11-15 09:13 UTC, stansfie commented on Software/Klipper/sgp40.py
>      "FEATURE_SET" : [0x20, 0x2F],
Great point! It's gone.

2023-11-15 09:19 UTC, stansfie commented
Thanks so much for your suggestions @SanaaHamel! Corrections have been made to the sgp40.py to address all of the above. Hope it's all more consistent now.

2023-11-15 17:51 UTC, SanaaHamel requested changes
Two last nitpicks, but I think it should be good to go afterwards.

2023-11-15 17:51 UTC, SanaaHamel commented on Software/Klipper/sgp40.py
> +           logging.exception("sgp40: Self test error")
This should be `logging.error` instead of `logging.exception`, `exception` attaches exception info and should only be used in a `except` block's scope,

2023-11-15 17:51 UTC, SanaaHamel commented on Software/Klipper/sgp40.py
> +            return {"temperature": self.voc * self.voc_scale }
For consistency, also scale the VOC value in the non-plot case?

2023-11-16 00:00 UTC, stansfie commented on Software/Klipper/sgp40.py
> +            return {"temperature": self.voc * self.voc_scale }
Done - VOC output is now scaled consistently independent of output type (plot_voc = TRUE | FALSE)

TL;DR I've left the sensor output as "voc"

Re: renaming output variables. I guess this is a question of accuracy, compatibility and semantics. Considering gas sensors are becoming more capable with multiple outputs (e.g., sgp30 - CO2 and VOC) specifying the input required for Nevermore fan/scrubber control algorithm may be the more future proof option rather than renaming the output of sensor modules to 'gas'.

Consider a hypothetical sensor that could output formaldehyde, VOC and ultrafine particle measures - VOC output could be used to control activated carbon scrubbing, formaldehyde output would require catalyst breakdown and ultrafine particle output would indicate the need for HEPA filtration. Maintaining accurate nomenclature here is useful in determining what needs to be run.

I think it makes sense to keep sensor output as specific as possible and allow flexible input options for the nevermore control algorithm.

2023-11-16 21:12 UTC, SanaaHamel approved these changes
LGTM

2023-11-18 16:49 UTC, merged